# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

keycloak:
  replicaCount: 1

database:
  description: "HA Postgres"

  image:
    repository: ghcr.io/cloudnative-pg/postgresql
    tag: 15.0

  replicaCount: 3

  storage:
    size: 10Gi
    storageClass: ""

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 512Mi

  enablePDB: true
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: false

  superuserSecret:
    {}

    # name: postgres-superuser

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      # secret:
      #   name: keycloak-user
      dataChecksums: true

  monitoring:
    enablePodMonitor: true

  backup:
    existingSecret:
      s3:
        name: cnpg-s3-creds
        credentialsKey: credentials
        configKey: config
        profileName: cnpg
    barmanObjectStore:
      destinationPath: "s3://bucket/path/to"
      wal:
        compression: gzip
        maxParallel: 4
    retentionPolicy: "7d"

  postgresql:
    parameters:
      shared_buffers: "64MB"
      max_wal_size: "256MB"
      wal_compression: "on"
      log_min_duration_statement: "500"
    pg_hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5

nodeSelector: {}

tolerations: []

affinity: {}
